CREATE TABLE order_item(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    created_date TIMESTAMP NOT NULL,
    product_id BIGINT REFERENCES product(id),
    order_id BIGINT REFERENCES _order(id),
    UNIQUE (product_id, order_id)
)